pipeline {

    agent any

    tools {
        maven 'Maven-3.9'
    }

    environment {
        DOCKER_IMAGE = "adeshprime17/interview-prep-hub"
    }

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    stages {

        stage('Checkout') {  // getting the source code 
            steps {
                echo 'Checking out source code...'
                checkout scm      //It refers to the system where your source code is stored
            }
        }

        stage('Build & Test') {
            steps {
                echo 'Building Spring Boot application...'

                dir('proj') {
                    bat 'mvn clean verify'
                }
            }

            post {  //  fter the pipeline or a stage finishes.
                always {    //regardless of whether the pipeline succeeds or fails.
                    junit(
                        testResults: 'proj/**/target/surefire-reports/*.xml',
                        allowEmptyResults: true
                    )
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'

                dir('proj') {
                    bat '''
                        docker build -t %DOCKER_IMAGE%:%BUILD_NUMBER% .
                        docker tag %DOCKER_IMAGE%:%BUILD_NUMBER% %DOCKER_IMAGE%:latest
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {

                echo 'Pushing Docker image to Docker Hub...'

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {

                    bat '''
                        echo Logging into Docker Hub...

                        docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD%

                        echo Pushing versioned image...
                        docker push %DOCKER_IMAGE%:%BUILD_NUMBER%

                        echo Pushing latest image...
                        docker push %DOCKER_IMAGE%:latest
                    '''
                }
            }
        }
    }

    post {

        always {
            bat 'docker logout || exit 0'
            echo 'Pipeline finished.'
        }

        success {
            echo 'CI Pipeline completed successfully!'
            echo "Docker image: %DOCKER_IMAGE%:%BUILD_NUMBER%"
            echo "Docker image: %DOCKER_IMAGE%:latest"
        }

        failure {
            echo 'CI Pipeline failed. Check the stage logs above.'
        }
    }
}
